# prometheus
global:
  scrape_interval: 5s
  evaluation_interval: 1m
# A scrape configuration scraping a Node Exporter and the Prometheus server itself
scrape_configs:
  # Scrape Prometheus itself every 10 seconds.
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['privateIP:9090']
  - job_name: 'Jenkin-slave'
    static_configs:
      - targets: ['privateIP:9100']
  - job_name: 'jenkins-master-exporter'
    static_configs:
      - targets: ['privateIP:9100']
  - job_name: 'cadvisor'
    static_configs:
       - targets: ['privateIP:8080']
  - job_name: 'Jenkins-master'
    metrics_path: /prometheus
    static_configs:
       - targets: ['privateIP:8080']
  - job_name: 'JMX'
    static_configs:
      - targets: ['privateIP:8081']
